Super_Admin_email=ashish.upadhyay@iffort.com
Super_Admin_password=Admin@1234
# ----------------------------
#  BROWSER SETTINGS
# ----------------------------
browser=edge			# Options: chrome, edge, firefox, safari
headless=false          # Run tests in headless mode (true/false)
maximize=true           # Maximize browser window on startup
isIncognito=true		# Run browser in incongito mode
# ----------------------------
#  DRIVER SETTINGS
# ----------------------------
implicit.wait=10      # Implicit wait time in seconds
page.load.timeout=30    # Page load timeout in seconds
script.timeout=30       # JavaScript execution timeout

# ----------------------------
#  APPLICATION UNDER TEST
# ----------------------------
base.url=http://shield.iffort.com/  # Application base URL

# ----------------------------
# \uD83D\uDD39 DATABASE CONFIGURATION
# ----------------------------
db.url=jdbc:mysql://localhost:3306/jdbc_test
db.username=root
db.password=
db.driver=com.mysql.cj.jdbc.Driver

# ----------------------------
#  TEST DATA & SQL QUERIES
# ----------------------------
test.data.path=./src/test/resources/org/test_data/test_data.properties
sql.queries.path=./src/test/resources/org/config/sql_queries.properties

# ----------------------------
#  LOGGING & REPORTING
# ----------------------------
enable.logs=true
enable.extent.reports=true
screenshot.path=./target/screenshots/
